/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AkAmbulanceWlList {
    }
}
declare global {
    interface HTMLAkAmbulanceWlListElement extends Components.AkAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLAkAmbulanceWlListElement: {
        prototype: HTMLAkAmbulanceWlListElement;
        new (): HTMLAkAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "ak-ambulance-wl-list": HTMLAkAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface AkAmbulanceWlList {
    }
    interface IntrinsicElements {
        "ak-ambulance-wl-list": AkAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ak-ambulance-wl-list": LocalJSX.IntrinsicElements["ak-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLAkAmbulanceWlListElement>;
        }
    }
}
